### ISSUE TITLE
Send plain text from file

### ISSUE THREAD

**Issue by NotMyFault** [tsickert/discord-webhook#11]
Heyo,

I was wondering if I can read the input from a file and send it to a channel, like using `raw-data` but without it being an embed?

Kind regards

**Comment by tsickert** [comment]
Hello,

Yup, you can do that! That json file can be any valid webhook body, so

```json
{
    "content": "foobar"
}
```

should do the trick!

**Comment by NotMyFault** [comment]
Thanks for the help!
