### ISSUE TITLE
Support amd64 platform

### ISSUE THREAD

**Issue by nopeless** [tsickert/discord-webhook#13]
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

@tsickert

**Comment by tsickert** [comment]
Hey @nopeless, sorry for the long delay, but I've been working to switch this action over to a JS action, which should eliminate this issue. I have a [release candidate](https://github.com/tsickert/discord-webhook/releases/tag/v5.0.0-RC) up that you can try out if you still want to use this action.

**Comment by nopeless** [comment]
> Hey @nopeless, sorry for the long delay, but I've been working to switch this action over to a JS action, which should eliminate this issue. I have a [release candidate](https://github.com/tsickert/discord-webhook/releases/tag/v5.0.0-RC) up that you can try out if you still want to use this action. 

I ended up with a different solution. Thanks for following up this issue though :+1:
