### ISSUE TITLE
Webhook should check status codes when deciding whether action succeeded

### ISSUE THREAD

**Issue by jonko0493** [tsickert/discord-webhook#162]
In [this code](https://github.com/tsickert/discord-webhook/blob/master/src/webhook.ts#L159-L170), the status code should be checked to ensure that it is a successful code (2xx). We received a 413 status code (Content Too Large) and the webhook action still succeeded (`successfully uploaded file with status code: 413`).

**Comment by tsickert** [comment]
Sorry for the issue! [v6.0.0](https://github.com/tsickert/discord-webhook/releases/tag/v6.0.0) implements `wait` by default, which should check the status of the executed webhook throw an exception if there's an issue. Let me know if that doesn't work for you and I can reopen and take a look
