### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by orome** [tsickert/discord-webhook#163]
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: tsickert/discord-webhook@v5.3.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by orome** [comment]
@tsickert Andy idea when this will get released?

**Comment by tsickert** [comment]
Done 😄 https://github.com/tsickert/discord-webhook/releases/tag/v5.5.0

**Comment by orome** [comment]
I still get:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: tsickert/discord-webhook@v5.5.0.
```

**Comment by tsickert** [comment]
You're right, looks like I missed a spot when upgrading. Reopening. I'll try to get a fix out ASAP

**Comment by tsickert** [comment]
Just giving an update, tried upgrading and the upload file functionality is failing and it looks like it's related to the node upgrade. Spent a while working on a fix and I think I was getting close but ran out of time. I'll pick it back up when I get a free moment. Sorry for the delay.

**Comment by tsickert** [comment]
Node 20 update done, the latest version is [v6.0.0](https://github.com/tsickert/discord-webhook/releases/tag/v6.0.0). Let me know if you see any issues

**Comment by orome** [comment]
Than's for fixing this so quickly! When will uploaded?

 I get:
 ```text
 Unable to resolve action `tsickert/discord-webhook@6.0.0`, unable to find version `6.0.0`
```

**Comment by tsickert** [comment]
No problem! Should be `tsickert/discord-webhook@v6.0.0` (with the `v` in front of `6.0.0`)

**Comment by orome** [comment]
🤦‍♂️ Somehow I'd deleted the `v` from (just) one of my uses. Thanks!
