### ISSUE TITLE
Action not suppoorted on macos-latest

### ISSUE THREAD

**Issue by ahnafnafee** [tsickert/discord-webhook#17]
I get the error `Error: Container action is only supported on Linux` when running an action in `macos-latest`

**Comment by tsickert** [comment]
Hey @ahnafnafee, thanks for submitting the issue. I've been working on adding OS support for all actions runners. I've got a [release candidate](https://github.com/tsickert/discord-webhook/releases/tag/v5.0.0-RC) up that you can use if you want to give it a shot.

**Comment by ahnafnafee** [comment]
> Hey @ahnafnafee, thanks for submitting the issue. I've been working on adding OS support for all actions runners. I've got a [release candidate](https://github.com/tsickert/discord-webhook/releases/tag/v5.0.0-RC) up that you can use if you want to give it a shot.

I'm currently trying to use `tsickert/discord-webhook@v5.0.0` but it says reference not found.
