### ISSUE TITLE
Upload A file

### ISSUE THREAD

**Issue by RitomG69** [tsickert/discord-webhook#4]
I want to upload a file how can I do that @

**Comment by tsickert** [comment]
Unfortunately, file uploads are not supported yet. 

I looked at the [API docs](https://discord.com/developers/docs/resources/webhook#execute-webhook) and it seems pretty simple to add. I'll add this as a feature request and I can try to take a look at it as soon as I can (I have a really busy weekend/week, so probably won't be that fast of a turn around)

**Comment by tsickert** [comment]
Alright, added file upload support in [v3.0.0](https://github.com/tsickert/discord-webhook/releases/tag/v3.0.0). 

Just add whatever file you want to upload into the action workspace and then set the `filename` action input. I provided an [example](https://github.com/marketplace/actions/discord-webhook-action#uploading-files) in the README. 

Feel free to reopen this or open a new issue if something isn't working.
