### ISSUE TITLE
Values seemingly not being used in webhook post

### ISSUE THREAD

**Issue by RedBrumbler** [tsickert/discord-webhook#6]
On my repository I tried configuring this so that it would post in a channel, the posting of the file seems to have worked completely fine, as seen here:

![afbeelding](https://user-images.githubusercontent.com/51795403/134475527-8b75111b-f351-4755-8e16-67a23434517e.png)

The issue lies in the fact that my action should be having a username, content and avatar-url set but in the logs made by the action I do not see these values in the discord json value, and I do not see them in the discord channel

this is my current configuration for the action:
![afbeelding](https://user-images.githubusercontent.com/51795403/134475640-5c03c30c-1c4a-47d4-8d55-0a14a6cc45a6.png)

[Linked here](https://github.com/RedBrumbler/MonkeComputer/blob/a300e406e1a69d9b19d7e2ff259515b2fb4ce7b0/.github/workflows/build-ndk.yml#L183-#L195)

I would expect this to update the text in the webhook accordingly, but it does not. Any pointers on why this would happen or what I am doing wrong would be appreciated

**Comment by RedBrumbler** [comment]
(Forgot to link the specific action run that is related to this)[https://github.com/RedBrumbler/MonkeComputer/runs/3684798957?check_suite_focus=true]

**Comment by tsickert** [comment]
Hey @RedBrumbler, I actually forgot to add those fields to the multipart form for file uploads. I just released a new version ([v3.1.0](https://github.com/marketplace/actions/discord-webhook-action?version=v3.1.0)) that should solve this for you, sorry about that!

**Comment by RedBrumbler** [comment]
ah, thanks! that explains my issues! I'll see if this fixes it

**Comment by RedBrumbler** [comment]
The username is now updated, the rest doesn't seem to be updated though

![afbeelding](https://user-images.githubusercontent.com/51795403/134485323-a0f62725-3b0b-4152-9ecb-018d45079cb3.png)

**Comment by RedBrumbler** [comment]
Checking the actions log shows that the avatar field is null and content field is empty

**Comment by RedBrumbler** [comment]
[linked here](https://github.com/RedBrumbler/MonkeComputer/runs/3686106551?check_suite_focus=true) is the action that doesn't get the content and avatar set now, is there some sort of override for if a file is posted?

**Comment by RedBrumbler** [comment]
interesting, right now the avatar field is null yet the field is properly set since the image appears, the content field is never set though which I assume is related to the filename overriding the content field, kind of like how raw-data would do ?
![afbeelding](https://user-images.githubusercontent.com/51795403/134497884-cdafc71d-a2f6-49b2-977b-0a8600cda7dd.png)

**Comment by tsickert** [comment]
The filename override was exactly why that was happening. I did test to see if the content could be provided with a file upload and it worked, so I added the content field in [v3.2.0](https://github.com/marketplace/actions/discord-webhook-action?version=v3.2.0). 

As far as the image goes, the action seems to be using `http://github.com/RedBrumbler/MonkeComputer.png`, which 404's (I think what you'd want to set is `http://github.com/RedBrumbler.png`). 

If that avatar is going to static (not sure if that's the intent since it's parameterized), then the webhook interface in Discord allows you to set a default image. Although, that may be what's happening already if it's showing up when the avatar is unset/invalid. 

Thanks for making this issue! I'm always looking to improve the action and this has been a big help ✨

**Comment by RedBrumbler** [comment]
My intention was to have the icon of the repository owner, but thats my own issue to fix, I'm glad I could help by bringing this to your attention though :)

**Comment by RedBrumbler** [comment]
haha thanks, it works a charm now 

![image](https://user-images.githubusercontent.com/51795403/134565604-e3fdb66c-6c21-4b5d-9f4b-b2ab01af39dd.png)

I've recommended this action to others in the communities I'm in as well, seeing as it's really useful for keeping action artifacts to private channels :)

**Comment by tsickert** [comment]
Awesome, glad it's working now!
